spring:
  application:
    name: movie-service
  datasource:
    url: jdbc:postgresql://localhost:5432/showscape
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
